from src.profile import CandidateProfile


candidate_profile = CandidateProfile(
    target_roles=[
        "Medicinal Chemist",
        "Scientist, Medicinal Chemistry",
        "Senior Scientist",
        "Principal Scientist",
        "Research Scientist",
        "Data Analyst",
        "Data Scientist",
        "Data Engineer",
        "Business Analyst",
    ],
    skills=[
        # Data / technology
        "python",
        "sql",
        "mysql",
        "pandas",
        "numpy",
        "fastapi",
        "react",
        "javascript",
        "spark",
        "airflow",
        "kafka",
        "docker",
        "git",
        "data analysis",
        "data engineering",
        # Chemistry / pharmaceutical
        "medicinal chemistry",
        "organic chemistry",
        "synthetic organic chemistry",
        "organic synthesis",
        "multi-step synthesis",
        "small molecules",
        "drug discovery",
        "lead optimization",
        "sar",
        "structure-based drug design",
        "molecular design",
        "protac",
        "targeted protein degradation",
        "degrader",
        "crbn",
        "vhl",
        "chemical biology",
        "western blot",
        "proteomics",
        "hplc",
        "lc-ms",
        "nmr",
        "antibody-drug conjugate",
        "degrader-antibody conjugate",
        "payload",
        "payload-linker",
        "inhibitor",
        "allosteric inhibitor",
        "biomarker",
    ],
    domains_by_track={
        "pharma": [
            "pharmaceutical",
            "biotech",
            "life sciences",
            "drug discovery",
            "medicinal chemistry",
            "oncology",
            "small molecule drug discovery",
            "targeted protein degradation",
            "antibody-drug conjugates",
            "chemical biology",
        ],
        "data": [
            "data analytics",
            "data engineering",
            "data science",
            "business analytics",
            "technology",
        ],
    },
    preferred_locations=[
        "Anywhere in USA",
    ],
    # Anywhere in USA reflects nationwide flexibility. Data experience is intentionally conservative;
    # data/analytics training and projects are skills, not professional years of data employment.
    experience_by_domain={
        "pharma": 8.0,
        "data": 0.0,
    },
)
